### basic settings ###
dataset: MNIST
n_train: 60000
n_test: 100
k: 5
mode: add
normalise_combined: False
compression_type: gzip
experiment_name: None
output_dir: /home/stephen/local_workdir/personal/gzip_results/default